events { }

http {
    server {
        listen 80;

        # Spring Boot 기본 경로 프록시
        location / {
            proxy_pass http://spring-boot:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Port $server_port; # 포트 정보 전달

        }

        # /chatbot 경로는 FastAPI 서버로 프록시
        location /chatbot/ {
            proxy_pass http://chatbot:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Port $server_port;

        }
    }
}
