spring.application.name=devBlog
server.port=8080
server.address=0.0.0.0

server.forward-headers-strategy=framework

spring.datasource.url=jdbc:mysql://localhost:3306/devBlog?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=***REMOVED***
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB
file.upload-dir=/Users/kimhanseop/Desktop/devBlog/src/main/resources/static/uploads

spring.mvc.hiddenmethod.filter.enabled=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.docker.compose.enabled=false

## Google 설정
spring.security.oauth2.client.registration.google.client-id=***REMOVED***
spring.security.oauth2.client.registration.google.client-secret=***REMOVED***
spring.security.oauth2.client.registration.google.scope[0]=email
spring.security.oauth2.client.registration.google.scope[1]=profile
